- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - python-pip

  - name: Install docker-compose
    pip:
        name: docker-compose


- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:

  - name: Launch hello world container is running
    docker_container:
        name: web_hello_world
        image: hello-world

